export enum Muscle {
  abdominals = 'abdominals',
  abductors = 'abductors',
  biceps = 'biceps',
  calves = 'calves',
  chest = 'chest',
  forearms = 'forearms',
  glutes = 'glutes',
  hamstrings = 'hamstrings',
  lats = 'lats',
 lowerBack = 'lower_back',
 middleBack = 'middle_back',
  neck = 'neck',
  quadriceps = 'quadriceps',
  traps = 'traps',
  triceps = 'triceps',
}
